repos:
- repo: local
  hooks:
    - id: trufflehog
      name: TruffleHog
      description: Detect secrets in your data.
      #entry: bash -c 'trufflehog git file://. --since-commit HEAD --fail'
      entry: bash -c 'docker run -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --fail'
      language: system
      language: system
      stages: ["commit", "push"]
