name: Bandit
on:
  pull_request:
  push:
    branches:
      - master #dev, release, etc.

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bandit
        uses: tj-actions/bandit@v5.1
        with:
          ignore_failure: true

