name: Bandit
on:
  workflow_dispatch:
  schedule: ## schedule the job to run at 12 am daily
     - cron: '0 0 * * *'

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bandit
        uses: tj-actions/bandit@v5.1
        with:
          ignore_failure: true

