name: Bandit
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bandit
        uses: tj-actions/bandit@v5.1
        with:
          ignore_failure: true

