name: Claude Security Review (Bedrock)

permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 2

      - name: Configure AWS (OIDC → assume role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::225285538696:role/bedrock-claude3
          aws-region: ${{ env.AWS_REGION }}

      - name: Claude Code security review
        uses: anthropics/claude-code-action@main
        with:
          comment-pr: "true"
          use_bedrock: "true"
          prompt: "/security-review"
          # pick your model (must match your IAM allowlist if you scoped it)
          claude_args: "--model anthropic.claude-sonnet-4-20250514-v1:0 --max-turns 6"
          github_token: ${{ github.token }}
