name: Nodejsscan
on:
  workflow_dispatch:
  schedule: ## schedule the job to run at 12 am daily
     - cron: '0 0 * * *'
     
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'
