name: Leaked Secrets Scan

on:
  workflow_dispatch:
  schedule: ## schedule the job to run at 12 am daily
     - cron: '0 0 * * *'

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
  #        path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
        continue-on-error: false
