name: trufflehog

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - master

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          scan: pr
        continue-on-error: false
